name: gestion_contacts
description: Application de gestion de contacts
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  go_router: ^14.2.0

  # Base de données locale
  sqflite: ^2.3.04
  sqflite_common_ffi: ^2.3.0  # ← AJOUTER CETTE LIGNE

  path: ^1.9.0

  # Sélection d’images
  image_picker: ^1.0.7

  # Stockage local (login)
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
